name: spread_regime_2501
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - defaults/osx-arm64::bzip2==1.0.8=h80987f9_6
  - ca-certificates==2025.11.12
  - conda-forge/osx-arm64::icu==75.1=hfee45f7_0
  - conda-forge/osx-arm64::libbrotlicommon==1.1.0=h6caf38d_4
  - conda-forge/osx-arm64::libcxx==21.1.2=hf598326_0
  - conda-forge/osx-arm64::libdeflate==1.24=h5773f1b_0
  - defaults/osx-arm64::libev==4.33=h1a28f6b_1
  - defaults/osx-arm64::libffi==3.4.4=hca03da5_1
  - conda-forge/osx-arm64::libiconv==1.18=h23cfdf5_2
  - defaults/osx-arm64::libjpeg-turbo==3.1.1=h79febb2_0
  - conda-forge/osx-arm64::liblzma==5.8.1=h39f12f2_2
  - defaults/osx-arm64::libmpdec==4.0.0=h80987f9_0
  - defaults/osx-arm64::libsodium==1.0.20=h897f8a9_0
  - conda-forge/osx-arm64::libwebp-base==1.6.0=h07db88b_0
  - defaults/osx-arm64::libzlib==1.3.1=h5f15de7_0
  - conda-forge/osx-arm64::llvm-openmp==21.1.2=h4a912ad_3
  - defaults/osx-arm64::lmdb==0.9.31=h79febb2_0
  - defaults/osx-arm64::lzo==2.10=h1a28f6b_2
  - defaults/osx-arm64::ncurses==6.5=hee39554_0
  - conda-forge/osx-arm64::pthread-stubs==0.4=hd74edd7_1002
  - defaults/osx-arm64::python_abi==3.13=1_cp313
  - defaults/noarch::tzdata==2025b=h04d1e81_0
  - defaults/osx-arm64::xorg-libxau==1.0.12=h3fc13f7_0
  - defaults/osx-arm64::xorg-libxdmcp==1.1.5=h3fc13f7_0
  - defaults/osx-arm64::yaml==0.2.5=h1a28f6b_0
  - defaults/osx-arm64::zlib-ng==2.0.7=h80987f9_0
  - defaults/osx-arm64::c-ares==1.34.5=h2ca31fc_0
  - defaults/osx-arm64::expat==2.7.1=h313beb8_0
  - defaults/osx-arm64::lerc==4.0.0=h313beb8_0
  - conda-forge/osx-arm64::libaec==1.1.4=h51d1e36_0
  - conda-forge/osx-arm64::libbrotlidec==1.1.0=h6caf38d_4
  - conda-forge/osx-arm64::libbrotlienc==1.1.0=h6caf38d_4
  - conda-forge/osx-arm64::libedit==3.1.20250104=pl5321hafb1f1b_0
  - defaults/osx-arm64::libgfortran5==11.3.0=h009349e_28
  - conda-forge/osx-arm64::liblzma-devel==5.8.1=h39f12f2_2
  - conda-forge/osx-arm64::libpng==1.6.50=h280e0eb_1
  - conda-forge/osx-arm64::libsqlite==3.50.4=h4237e3c_0
  - defaults/osx-arm64::libxcb==1.17.0=h3fc13f7_0
  - conda-forge/osx-arm64::libxml2-16==2.15.0=h0ff4647_1
  - defaults/osx-arm64::lz4-c==1.9.4=h313beb8_1
  - openssl==3.6.0
  - defaults/osx-arm64::qhull==2020.2=h48ca7d4_2
  - defaults/osx-arm64::readline==8.3=h0b18652_0
  - conda-forge/osx-arm64::snappy==1.2.2=hd121638_0
  - conda-forge/osx-arm64::xz-gpl-tools==5.8.1=h9a6d368_2
  - conda-forge/osx-arm64::xz-tools==5.8.1=h39f12f2_2
  - defaults/osx-arm64::zeromq==4.3.5=h2c7f8f0_1
  - defaults/osx-arm64::zlib==1.3.1=h5f15de7_0
  - conda-forge/osx-arm64::brotli-bin==1.1.0=h6caf38d_4
  - conda-forge/osx-arm64::libfreetype6==2.14.1=h6da58f4_0
  - defaults/osx-arm64::libgfortran==5.0.0=11_3_0_hca03da5_28
  - defaults/osx-arm64::libkrb5==1.21.3=h73ed823_4
  - conda-forge/osx-arm64::libnghttp2==1.67.0=hc438710_0
  - defaults/osx-arm64::libssh2==1.11.1=h3e2b118_0
  - conda-forge/osx-arm64::libxml2==2.15.0=h9329255_1
  - defaults/osx-arm64::pandoc==3.8=hca03da5_0
  - defaults/osx-arm64::sqlite==3.50.2=h79febb2_1
  - defaults/osx-arm64::tk==8.6.15=hcd8a7d5_0
  - conda-forge/osx-arm64::xz==5.8.1=h9a6d368_2
  - conda-forge/osx-arm64::brotli==1.1.0=h6caf38d_4
  - defaults/osx-arm64::krb5==1.21.3=h95cc1b6_4
  - conda-forge/osx-arm64::libfreetype==2.14.1=hce30654_0
  - defaults/osx-arm64::libopenblas==0.3.30=hf2bb037_0
  - conda-forge/osx-arm64::libxslt==1.1.43=hb2570ba_1
  - defaults/osx-arm64::python==3.13.7=hc28b8d9_100_cp313
  - defaults/osx-arm64::zstd==1.5.7=h817c040_0
  - defaults/noarch::appdirs==1.4.4=pyhd3eb1b0_0
  - defaults/osx-arm64::appnope==0.1.4=py313hca03da5_0
  - defaults/osx-arm64::asttokens==3.0.0=py313hca03da5_0
  - conda-forge/noarch::attrs==25.4.0=pyh71513ae_0
  - defaults/osx-arm64::blinker==1.9.0=py313hca03da5_0
  - defaults/osx-arm64::blosc==1.21.6=h7977b18_0
  - conda-forge/osx-arm64::brotli-python==1.1.0=py313hb4b7877_4
  - defaults/osx-arm64::c-blosc2==2.17.1=hca023f9_0
  - defaults/osx-arm64::cached-property==2.0.1=py313hca03da5_0
  - conda-forge/noarch::cached_property==1.5.2=pyha770c72_1
  - certifi==2025.11.12
  - conda-forge/noarch::charset-normalizer==3.4.3=pyhd8ed1ab_0
  - conda-forge/noarch::click==8.3.0=pyh707e725_0
  - defaults/osx-arm64::colorama==0.4.6=py313hca03da5_0
  - conda-forge/noarch::comm==0.2.3=pyhe01879c_0
  - conda-forge/noarch::cpython==3.13.7=py313hd8ed1ab_100
  - conda-forge/noarch::cycler==0.12.1=pyhd8ed1ab_1
  - conda-forge/osx-arm64::debugpy==1.8.17=py313hc37fe24_0
  - defaults/osx-arm64::decorator==5.2.1=py313hca03da5_0
  - defaults/noarch::defusedxml==0.7.1=pyhd3eb1b0_0
  - defaults/osx-arm64::et_xmlfile==2.0.0=py313hca03da5_0
  - defaults/osx-arm64::executing==2.2.1=py313hca03da5_0
  - defaults/osx-arm64::fonttools==4.60.1=py313h254cc4a_0
  - conda-forge/osx-arm64::freetype==2.14.1=hce30654_0
  - conda-forge/osx-arm64::frozendict==2.4.6=py313hcdf3177_1
  - defaults/osx-arm64::greenlet==3.2.4=py313h0962b89_0
  - defaults/osx-arm64::h11==0.16.0=py313hca03da5_0
  - defaults/osx-arm64::hpack==4.1.0=py313hca03da5_0
  - defaults/osx-arm64::hyperframe==6.1.0=py313hca03da5_0
  - conda-forge/noarch::idna==3.10=pyhd8ed1ab_1
  - defaults/osx-arm64::iniconfig==2.1.0=py313hca03da5_0
  - defaults/osx-arm64::itsdangerous==2.2.0=py313hca03da5_0
  - defaults/osx-arm64::joblib==1.5.2=py313hca03da5_0
  - conda-forge/noarch::json5==0.12.1=pyhd8ed1ab_0
  - defaults/osx-arm64::jsonpointer==3.0.0=py313hca03da5_0
  - defaults/osx-arm64::jupyterlab_widgets==3.0.15=py313hca03da5_0
  - conda-forge/osx-arm64::kiwisolver==1.4.9=py313hf88c9ab_1
  - conda-forge/noarch::lark==1.3.0=pyhd8ed1ab_0
  - conda-forge/osx-arm64::libblas==3.9.0=36_h51639a9_openblas
  - defaults/osx-arm64::libcurl==8.15.0=hcdd2897_0
  - conda-forge/osx-arm64::libtiff==4.7.1=h7dc4979_0
  - conda-forge/osx-arm64::llvmlite==0.45.1=py313he297ed2_0
  - conda-forge/osx-arm64::lxml==6.0.2=py313he6cafaa_1
  - conda-forge/osx-arm64::markupsafe==3.0.3=py313h7d74516_0
  - defaults/osx-arm64::multitasking==0.0.12=py313hca03da5_0
  - defaults/noarch::munkres==1.1.4=py_0
  - defaults/osx-arm64::narwhals==2.7.0=py313hca03da5_0
  - defaults/osx-arm64::nest-asyncio==1.6.0=py313hca03da5_0
  - defaults/osx-arm64::networkx==3.5=py313hca03da5_0
  - defaults/osx-arm64::packaging==25.0=py313hca03da5_0
  - defaults/osx-arm64::pandocfilters==1.5.1=py313hca03da5_0
  - conda-forge/noarch::parso==0.8.5=pyhcf101f3_0
  - defaults/osx-arm64::peewee==3.18.2=py313hbe2cdee_0
  - defaults/noarch::pickleshare==0.7.5=pyhd3eb1b0_1003
  - conda-forge/noarch::platformdirs==4.5.0=pyhcf101f3_0
  - conda-forge/noarch::pluggy==1.6.0=pyhd8ed1ab_0
  - conda-forge/noarch::prometheus_client==0.23.1=pyhd8ed1ab_0
  - conda-forge/osx-arm64::psutil==7.1.0=py313h6535dbc_0
  - defaults/noarch::ptyprocess==0.7.0=pyhd3eb1b0_2
  - defaults/osx-arm64::pure_eval==0.2.3=py313hca03da5_0
  - defaults/osx-arm64::py-cpuinfo==9.0.0=py313hca03da5_0
  - defaults/osx-arm64::pycparser==2.23=py313hca03da5_0
  - conda-forge/noarch::pygments==2.19.2=pyhd8ed1ab_0
  - conda-forge/noarch::pyparsing==3.2.5=pyhcf101f3_0
  - defaults/osx-arm64::pysocks==1.7.1=py313hca03da5_0
  - conda-forge/noarch::python-fastjsonschema==2.21.2=pyhe01879c_0
  - defaults/noarch::python-gil==3.13.7=py313h13117d0_100
  - defaults/osx-arm64::python-json-logger==3.2.1=py313hca03da5_0
  - defaults/noarch::python-tzdata==2025.2=pyhd3eb1b0_0
  - defaults/osx-arm64::pytz==2025.2=py313hca03da5_0
  - conda-forge/osx-arm64::pyyaml==6.0.3=py313h7d74516_0
  - defaults/osx-arm64::pyzmq==27.1.0=py313h854a7ef_0
  - conda-forge/noarch::retrying==1.4.2=pyhe01879c_0
  - defaults/osx-arm64::rfc3986-validator==0.1.1=py313hca03da5_0
  - conda-forge/osx-arm64::rpds-py==0.27.1=py313h80e0809_1
  - defaults/osx-arm64::setuptools==72.1.0=py313hca03da5_0
  - defaults/osx-arm64::six==1.17.0=py313hca03da5_0
  - conda-forge/noarch::sniffio==1.3.1=pyhd8ed1ab_1
  - conda-forge/noarch::soupsieve==2.8=pyhd8ed1ab_0
  - defaults/osx-arm64::tabulate==0.9.0=py313hca03da5_0
  - conda-forge/noarch::threadpoolctl==3.6.0=pyhecae5ae_0
  - conda-forge/noarch::tomli==2.3.0=pyhcf101f3_0
  - conda-forge/osx-arm64::tornado==6.5.2=py313hcdf3177_1
  - defaults/osx-arm64::tqdm==4.67.1=py313h7eb115d_0
  - defaults/osx-arm64::traitlets==5.14.3=py313hca03da5_0
  - conda-forge/noarch::types-python-dateutil==2.9.0.20251008=pyhd8ed1ab_0
  - defaults/osx-arm64::typing_extensions==4.15.0=py313hca03da5_0
  - conda-forge/noarch::typing_utils==0.1.0=pyhd8ed1ab_1
  - conda-forge/noarch::uri-template==1.3.0=pyhd8ed1ab_1
  - conda-forge/noarch::wcwidth==0.2.14=pyhd8ed1ab_0
  - conda-forge/noarch::webcolors==24.11.1=pyhd8ed1ab_0
  - defaults/osx-arm64::webencodings==0.5.1=py313hca03da5_2
  - conda-forge/noarch::websocket-client==1.9.0=pyhd8ed1ab_0
  - defaults/osx-arm64::wheel==0.45.1=py313hca03da5_0
  - conda-forge/noarch::widgetsnbextension==4.0.14=pyhd8ed1ab_0
  - defaults/noarch::xlrd==2.0.2=pyhd3eb1b0_0
  - defaults/osx-arm64::xyzservices==2025.4.0=py313hca03da5_0
  - conda-forge/noarch::zipp==3.23.0=pyhd8ed1ab_0
  - conda-forge/noarch::_python_abi3_support==1.0=hd8ed1ab_2
  - conda-forge/noarch::async-lru==2.0.5=pyh29332c3_0
  - conda-forge/noarch::babel==2.17.0=pyhd8ed1ab_0
  - conda-forge/noarch::bleach==6.2.0=pyh29332c3_4
  - defaults/osx-arm64::cffi==2.0.0=py313h3a083c1_0
  - conda-forge/noarch::exceptiongroup==1.3.0=pyhd8ed1ab_0
  - conda-forge/noarch::fqdn==1.5.1=pyhd8ed1ab_1
  - conda-forge/noarch::h2==4.3.0=pyhcf101f3_0
  - defaults/osx-arm64::hdf5==1.14.5=hd77251f_2
  - defaults/noarch::html5lib==1.1=pyhd3eb1b0_0
  - defaults/osx-arm64::httpcore==1.0.9=py313hca03da5_0
  - conda-forge/noarch::importlib-metadata==8.7.0=pyhe01879c_1
  - defaults/osx-arm64::ipython_pygments_lexers==1.1.1=py313hca03da5_0
  - defaults/osx-arm64::jedi==0.19.2=py313hca03da5_0
  - defaults/osx-arm64::jinja2==3.1.6=py313hca03da5_0
  - defaults/osx-arm64::jupyter_core==5.8.1=py313hca03da5_0
  - defaults/osx-arm64::jupyterlab_pygments==0.3.0=py313hca03da5_0
  - conda-forge/osx-arm64::lcms2==2.17=h7eeda09_0
  - conda-forge/osx-arm64::libcblas==3.9.0=36_hb0561ab_openblas
  - conda-forge/osx-arm64::liblapack==3.9.0=36_hd9741b5_openblas
  - defaults/osx-arm64::matplotlib-inline==0.1.7=py313hca03da5_0
  - conda-forge/noarch::mistune==3.1.4=pyhcf101f3_0
  - conda-forge/osx-arm64::openjpeg==2.5.4=hbfb3c88_0
  - defaults/osx-arm64::openpyxl==3.1.5=py313h80987f9_1
  - conda-forge/noarch::overrides==7.7.0=pyhd8ed1ab_1
  - defaults/osx-arm64::pexpect==4.9.0=py313hca03da5_0
  - defaults/noarch::pip==25.2=pyhc872135_0
  - conda-forge/noarch::plotly==6.3.1=pyhd8ed1ab_0
  - conda-forge/noarch::prompt-toolkit==3.0.52=pyha770c72_0
  - conda-forge/osx-arm64::pyobjc-core==11.0=py313hb6afeec_0
  - defaults/osx-arm64::pytest==8.4.2=py313hca03da5_0
  - defaults/osx-arm64::python-dateutil==2.9.0post0=py313hca03da5_2
  - defaults/osx-arm64::qtpy==2.4.3=py313hca03da5_0
  - conda-forge/noarch::referencing==0.36.2=pyh29332c3_0
  - defaults/osx-arm64::rfc3339-validator==0.1.4=py313hca03da5_0
  - conda-forge/noarch::rfc3987-syntax==1.1.0=pyhe01879c_1
  - defaults/osx-arm64::stack_data==0.6.3=py313hca03da5_0
  - defaults/osx-arm64::terminado==0.18.1=py313hca03da5_0
  - defaults/osx-arm64::tinycss2==1.4.0=py313hca03da5_0
  - defaults/osx-arm64::typing-extensions==4.15.0=py313hca03da5_0
  - defaults/osx-arm64::werkzeug==3.1.3=py313hca03da5_0
  - conda-forge/noarch::anyio==4.11.0=pyhcf101f3_0
  - defaults/osx-arm64::argon2-cffi-bindings==25.1.0=py313h254cc4a_0
  - defaults/osx-arm64::arrow==1.3.0=py313hca03da5_0
  - conda-forge/noarch::beautifulsoup4==4.14.2=pyha770c72_0
  - conda-forge/noarch::bleach-with-css==6.2.0=h82add2a_4
  - defaults/osx-arm64::brotlicffi==1.0.9.2=py313h313beb8_1
  - defaults/osx-arm64::flask==3.1.2=py313hca03da5_0
  - conda-forge/noarch::ipython==9.6.0=pyhfa0c392_0
  - conda-forge/noarch::jsonschema-specifications==2025.9.1=pyhcf101f3_0
  - defaults/osx-arm64::jupyter_client==8.6.3=py313hca03da5_0
  - defaults/osx-arm64::jupyter_server_terminals==0.5.3=py313hca03da5_0
  - conda-forge/osx-arm64::liblapacke==3.9.0=36_h1b118fd_openblas
  - conda-forge/osx-arm64::pillow==11.3.0=py313he4c6d0d_3
  - conda-forge/noarch::prompt_toolkit==3.0.52=hd8ed1ab_0
  - conda-forge/osx-arm64::pyobjc-framework-cocoa==11.0=py313hb6afeec_0
  - conda-forge/osx-arm64::sqlalchemy==2.0.44=py313h6535dbc_0
  - conda-forge/osx-arm64::zstandard==0.25.0=py313h9734d34_0
  - conda-forge/noarch::argon2-cffi==25.1.0=pyhd8ed1ab_0
  - defaults/osx-arm64::httpx==0.28.1=py313hca03da5_0
  - defaults/osx-arm64::ipykernel==6.30.1=py313hca03da5_0
  - conda-forge/noarch::ipywidgets==8.1.7=pyhd8ed1ab_0
  - conda-forge/noarch::isoduration==20.11.0=pyhd8ed1ab_1
  - conda-forge/noarch::jsonschema==4.25.1=pyhe01879c_0
  - conda-forge/noarch::send2trash==1.8.3=pyh31c8845_1
  - defaults/osx-arm64::urllib3==2.5.0=py313hca03da5_0
  - conda-forge/noarch::jsonschema-with-format-nongpl==4.25.1=he01879c_0
  - defaults/osx-arm64::jupyter_console==6.6.3=py313hca03da5_1
  - defaults/osx-arm64::jupyter_events==0.12.0=py313hca03da5_0
  - defaults/osx-arm64::nbformat==5.10.4=py313hca03da5_0
  - defaults/osx-arm64::qtconsole==5.7.0=py313hca03da5_0
  - defaults/osx-arm64::requests==2.32.5=py313hca03da5_0
  - conda-forge/noarch::dash==3.2.0=pyhd8ed1ab_0
  - defaults/osx-arm64::nbclient==0.10.2=py313hca03da5_0
  - defaults/osx-arm64::nbconvert-core==7.16.6=py313hca03da5_0
  - conda-forge/noarch::jupyter_server==2.17.0=pyhcf101f3_0
  - defaults/osx-arm64::nbconvert-pandoc==7.16.6=py313hca03da5_0
  - conda-forge/noarch::jupyter-lsp==2.3.0=pyhcf101f3_0
  - defaults/osx-arm64::jupyterlab_server==2.27.3=py313hca03da5_0
  - defaults/osx-arm64::nbconvert==7.16.6=py313hca03da5_0
  - defaults/osx-arm64::notebook-shim==0.2.4=py313hca03da5_0
  - jupyterlab==4.4.10
  - conda-forge/noarch::notebook==7.4.7=pyhd8ed1ab_0
  - defaults/osx-arm64::jupyter==1.1.1=py313hca03da5_0
  - conda-forge/osx-arm64::blas==2.136=openblas
  - defaults/osx-arm64::nomkl==3.0=0
  - defaults/osx-arm64::numpy-base==2.3.3=py313h23175f9_0
  - numpy
  - defaults/osx-arm64::openblas-devel==0.3.30=h1465027_0
  - defaults/osx-arm64::bottleneck==1.4.2=py313ha35b7ea_0
  - conda-forge/osx-arm64::contourpy==1.3.3=py313hc50a443_2
  - conda-forge/osx-arm64::numba==0.62.1=py313h936dde2_0
  - conda-forge/osx-arm64::numexpr==2.13.1=py313h73ed539_1
  - defaults/osx-arm64::openblas==0.3.30=hb03180a_0
  - defaults/osx-arm64::patsy==1.0.1=py313hca03da5_0
  - defaults/osx-arm64::scipy==1.16.2=py313h08a1045_0
  - conda-forge/osx-arm64::blas-devel==3.9.0=36_h11c0a38_openblas
  - defaults/osx-arm64::matplotlib-base==3.10.6=py313h8596600_0
  - pandas==2.3.3
  - defaults/osx-arm64::pytables==3.10.2=py313h8397fff_2
  - scikit-learn==1.7.2
  - defaults/osx-arm64::bokeh==3.8.0=py313hca03da5_0
  - matplotlib==3.10.6
  - defaults/noarch::pandas-datareader==0.10.0=pyhd3eb1b0_0
  - seaborn==0.13.2
  - statsmodels==0.14.6
  - conda-forge/noarch::yfinance==0.2.57=pyhd8ed1ab_0
  - conda-forge/noarch::quantstats==0.0.62=pyhd8ed1ab_1
  - fredapi
  - python-dotenv
prefix: /opt/anaconda3/envs/spread_regime_2501
